# Generated by Django 3.2.13 on 2022-06-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_post_postphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_user',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postphotos',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='images/%Y-%m-%d/'),
        ),
    ]
