# Generated by Django 3.2.13 on 2022-06-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220608_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='completed',
        ),
    ]
