# Generated by Django 3.2.13 on 2022-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_post_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphotos',
            name='cover',
            field=models.ImageField(default='default.png', upload_to='images/%Y-%m-%d/'),
        ),
    ]
