# Generated by Django 3.2.13 on 2022-06-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220619_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.BigIntegerField()),
                ('cover', models.ImageField(default='default.png', upload_to='profile_photo/%Y-%m-%d/')),
            ],
        ),
    ]
